name: Auto Update Grafana allowlist IPs

on:
  schedule:
  # Cron job every 1 hour is a commonly used cron schedule.
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        architecture: 'x64'
    - name: Setup pip
      run: |
        python -m pip install --upgrade pip
        pip install requests boto3
    - name: Run python script
      run: |
        python scripts/test.py